[package]
name = "nftnl"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>"]
license = "MIT/Apache-2.0"
description = "Safe abstraction for libnftnl. Provides low-level userspace access to the in-kernel nf_tables subsystem"
repository = "https://github.com/mullvad/nftnl-rs"
keywords = ["nftables", "nft", "firewall", "iptables", "netfilter"]
categories = ["network-programming", "os::unix-apis", "api-bindings"]

[features]
nftnl-1-0-7 = ["nftnl-sys/nftnl-1-0-7"]
nftnl-1-0-8 = ["nftnl-sys/nftnl-1-0-8"]
nftnl-1-0-9 = ["nftnl-sys/nftnl-1-0-9"]
nftnl-1-1-0 = ["nftnl-sys/nftnl-1-1-0"]
nftnl-1-1-1 = ["nftnl-sys/nftnl-1-1-1"]

[dependencies]
bitflags = "1.0"
error-chain = "0.12"
libc = "0.2.40"
log = "0.4"
nftnl-sys = { path = "../nftnl-sys", version = "0.1" }
