# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:alpine"

# clang-libs are needed by bindgen. build-base contains various needed things,
# among which crti.o and pkg-config.
before_script:
  - apk update
  - apk add build-base libmnl-dev libnftnl-dev clang-libs

cache:
  paths:
    - target/
    - cargo/

variables:
  # Set CARGO_HOME inside the CI directory, otherwise cargo won't use the cache.
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  # Let rust create dynamically linked builds under musl libc - see [this rust
  # issue](https://github.com/rust-lang/compiler-team/issues/422)
  RUSTFLAGS: "-C target-feature=-crt-static"
    # Same consideration for doc tests - see [this rust
    # issue](https://github.com/rust-lang/cargo/issues/6650)
  RUSTDOCFLAGS: "-C target-feature=-crt-static"

test:cargo:
  script:
    - mkdir -p target cargo
    - du -sh target cargo
    - rustc --version && cargo --version
    - cargo test --workspace --verbose --release

