# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
before_script:
   - apt-get update -yqq
   - apt-get --yes install libmnl-dev libnftnl-dev

cache:
  paths:
    - target/
    - cargo/

# Set CARGO_HOME inside the CI directory, otherwise cargo won't use the cache.
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
  script:
    - mkdir -p target cargo
    - du -sh target cargo
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose --release

